# NOTE: there is no such thing as a working "by-default" configuration file. 
#       At least the prefix needs to be specified.  Please consult the radvd.conf(5)
#       man page and/or /usr/share/doc/radvd-*/radvd.conf.example for help.
#
#
interface eth0
{
    AdvSendAdvert on;
    MinRtrAdvInterval 1350;
    MaxRtrAdvInterval 1800;
    AdvDefaultLifetime 0;
    AdvDefaultPreference low;
    # The lowest priority resolver for a client, compliant with RFC 8106 Sec.5.3.1. (exc. systemd-resolved DNSStubListener=yes)
    RDNSS 2404:1a8:7f01:a::3 2404:1a8:7f01:b::3 {
        AdvRDNSSLifetime infinity;
        FlushRDNSS off;
    };
    route 64:ff9b:1::/48 {};
    # Cloudflare Free Tier
    route 2606:4700:3030::/45 {};
    # dns.google
    route 2001:4860:4840::/42 {};
    # one.one.one.one
    route 2606:4700:4700::/40 {};
    route 2a06:98c1:50::/45 {};
    # dns.opendns.com
    route 2620:0:ccc::/47 {};
    route 2620:119:17::/48 {};
    route 2620:119:35::/48 {};
    route 2620:119:53::/48 {};
    route 2620:119:76::/48 {};
    route 2620:119:fc::/48 {};
    route 2a04:e4c0:170::/47 {};
    # html-load.com
    route 2606:4700::6812:1400/119 {};
    # https://www.spamhaus.org/blocklists/do-not-route-or-peer/#how-it-works
    # iOS 26.5 ignores legitimate RA messages when it receives a rogue RA packet containing many PIOs. RIOs work.
    # Windows 11 will experience IPv6 failure when it receives a rogue RA packet containing many AdvRouteLifetime > 0 RIOs. PIOs work.
};
