# NOTE: there is no such thing as a working "by-default" configuration file. 
#       At least the prefix needs to be specified.  Please consult the radvd.conf(5)
#       man page and/or /usr/share/doc/radvd-*/radvd.conf.example for help.
#
#
interface eth0
{
	AdvSendAdvert on;
	MinRtrAdvInterval 1350;
	MaxRtrAdvInterval 1800;
	AdvDefaultLifetime 0;
	AdvDefaultPreference low;
    prefix 64:ff9b:1::/48
    {
		AdvOnLink on;
		AdvAutonomous off;
		AdvRouterAddr off;
	};
};
