# NOTE: there is no such thing as a working "by-default" configuration file. 
#       At least the prefix needs to be specified.  Please consult the radvd.conf(5)
#       man page and/or /usr/share/doc/radvd-*/radvd.conf.example for help.
#
#
interface eth0
{
    AdvSendAdvert on;
    MinRtrAdvInterval 1350;
    MaxRtrAdvInterval 1800;
    AdvDefaultLifetime 0;
    AdvDefaultPreference low;
    # The lowest priority resolver for a client, compliant with RFC 8106 Sec.5.3.1. (exc. systemd-resolved DNSStubListener=yes)
    RDNSS 2404:1a8:7f01:a::3 2404:1a8:7f01:b::3 {
        AdvRDNSSLifetime 179; # https://cs.android.com/android/_/android/platform/packages/modules/NetworkStack/+/cbe1060e7d4717c1f3e4a5ac3268be2f7afc0456:src/android/net/ip/IpClient.java;dlc=07628782a699923189bd584cf69c06d1dfabd03b
    };
    prefix 64:ff9b:1::/48
    {
        AdvOnLink on;
        AdvAutonomous off;
        AdvRouterAddr off;
    };
    # Cloudflare Free Tier
    prefix 2606:4700:3030::/45
    {
        AdvOnLink on;
        AdvAutonomous off;
        AdvRouterAddr off;
    };
    # dns.google
    prefix 2001:4860:4840::/42
    {
        AdvOnLink on;
        AdvAutonomous off;
        AdvRouterAddr off;
    };
    # one.one.one.one
    prefix 2606:4700:4700::/40
    {
        AdvOnLink on;
        AdvAutonomous off;
        AdvRouterAddr off;
    };
    # html-load.com
    prefix 2606:4700::6812:1400/119
    {
        AdvOnLink on;
        AdvAutonomous off;
        AdvRouterAddr off;
    };
    # https://www.spamhaus.org/blocklists/do-not-route-or-peer/#how-it-works
    # iOS 26.5 ignores legitimate RA messages when it receives 1 < Rogue RA packet. Therefore, the "DROP" list cannot be used.
};
