# Uncomment the include statement here to load the default config sample
# in /etc/nftables for nftables service.

#include "/etc/nftables/main.nft"

# To customize, either edit the samples in /etc/nftables, append further
# commands to the end of this file or overwrite it after first service
# start by calling: 'nft list ruleset >/etc/sysconfig/nftables.conf'.
table inet nat64 {

  chain postrouting {
    type nat hook postrouting priority srcnat;

    # tayga@pp01
    ip saddr 192.168.1.0/24 oif "eth0" snat to 10.64.8.1
    # tayga@tu10
    ip saddr 192.168.10.0/24 oif "eth0" snat to 10.64.8.10
    # tayga@tu20
    ip saddr 192.168.20.0/24 oif "eth0" snat to 10.64.8.20
  }

  chain forward {
    type filter hook forward priority 0;

    # 内->外
    iifname "nat64pp01" oifname "eth0" accept
    iifname "nat64tu10" oifname "eth0" accept
    iifname "nat64tu20" oifname "eth0" accept

    # 外->内 (establishedのみ)
    iifname "eth0" oifname "nat64pp01" ct state related,established accept
    iifname "eth0" oifname "nat64tu10" ct state related,established accept
    iifname "eth0" oifname "nat64tu20" ct state related,established accept
  }
}
