# Uncomment the include statement here to load the default config sample
# in /etc/nftables for nftables service.

#include "/etc/nftables/main.nft"

# To customize, either edit the samples in /etc/nftables, append further
# commands to the end of this file or overwrite it after first service
# start by calling: 'nft list ruleset >/etc/sysconfig/nftables.conf'.
table inet nat64 {
  chain postrouting {
    type nat hook postrouting priority srcnat;
    ip saddr 192.168.255.0/24 oif "eth0" masquerade
  }

  chain forward {
    type filter hook forward priority 0;

    iifname "nat64" oifname "eth0" accept
    iifname "eth0" oifname "nat64" ct state related,established accept
  }
}
